import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/association_rule.dart';
import '../providers/detection_provider.dart';

class RulesChartScreen extends ConsumerStatefulWidget {
  const RulesChartScreen({super.key});

  @override
  ConsumerState<RulesChartScreen> createState() => _RulesChartScreenState();
}

class _RulesChartScreenState extends ConsumerState<RulesChartScreen> {
  final ruleSets = const {
    'minSup 0.10 / minConf 0.60': 'stage4-v1-fpgrowth-01-06',
    'minSup 0.10 / minConf 0.80': 'stage4-v1-fpgrowth-01-08',
    'minSup 0.05 / minConf 0.60': 'stage4-v1-fpgrowth-005-06',
    'minSup 0.05 / minConf 0.80': 'stage4-v1-fpgrowth-005-08',
  };
  String selected = 'stage4-v1-fpgrowth-01-06';
  List<AssociationRule> rules = [];
  bool loading = false;
  String? error;

  @override
  void initState() {
    super.initState();
    load();
  }

  Future<void> load() async {
    setState(() {
      loading = true;
      error = null;
    });
    try {
      final value = await ref.read(ruleServiceProvider).getRules(selected);
      if (mounted) setState(() => rules = value);
    } catch (value) {
      if (mounted) setState(() => error = value.toString());
    } finally {
      if (mounted) setState(() => loading = false);
    }
  }

  String get graphAsset => 'assets/arm_graphs/$selected.png';

  @override
  Widget build(BuildContext context) {
    final graphRules = rules
        .where((rule) => rule.consequent.isNotEmpty)
        .take(20)
        .toList();
    return Scaffold(
      appBar: AppBar(title: const Text('FP-Growth Association Rule Graph')),
      body: ListView(
        padding: const EdgeInsets.all(24),
        children: [
          Text(
            'Python-generated association rule graph',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          const Text(
            'The graph is generated by Scripts/plot_arm_graph.py. Edge width represents rule confidence.',
          ),
          const SizedBox(height: 20),
          DropdownButtonFormField<String>(
            initialValue: selected,
            decoration: const InputDecoration(
              labelText: 'FP-Growth threshold',
              border: OutlineInputBorder(),
            ),
            items: [
              for (final entry in ruleSets.entries)
                DropdownMenuItem(value: entry.value, child: Text(entry.key)),
            ],
            onChanged: loading
                ? null
                : (value) {
                    if (value == null) return;
                    setState(() => selected = value);
                    load();
                  },
          ),
          if (loading)
            const Padding(
              padding: EdgeInsets.only(top: 16),
              child: LinearProgressIndicator(),
            ),
          if (error != null)
            Padding(
              padding: const EdgeInsets.only(top: 16),
              child: Text(
                error!,
                style: TextStyle(color: Theme.of(context).colorScheme.error),
              ),
            ),
          const SizedBox(height: 20),
          InteractiveViewer(
            minScale: 0.5,
            maxScale: 4,
            child: Image.asset(
              graphAsset,
              height: 560,
              fit: BoxFit.contain,
              errorBuilder: (_, _, _) => const Padding(
                padding: EdgeInsets.all(24),
                child: Text(
                  'Graph image not found. Run:\n'
                  'python Scripts/plot_arm_graph.py',
                  textAlign: TextAlign.center,
                ),
              ),
            ),
          ),
          const SizedBox(height: 12),
          const Text(
            'Thin edge = lower confidence | Thick edge = higher confidence',
          ),
          const SizedBox(height: 16),
          for (final rule in graphRules)
            Card(
              child: ListTile(
                title: Text(
                  '${rule.antecedent.map(featureName).join(' + ')} -> ${rule.consequent.map(featureName).join(' + ')}',
                ),
                subtitle: Text(
                  'Support ${rule.support} | Confidence ${(rule.confidence * 100).toStringAsFixed(2)}%',
                ),
              ),
            ),
        ],
      ),
    );
  }
}

String featureName(int item) {
  const names = {
    1: 'LONG_LEN',
    2: 'HIGH_SYMBOL',
    3: 'ZERO_COMPARISON',
    30: 'LOW_COMPARISON',
    33: 'HIGH_COMPARISON',
    40: 'COMPLEXITY_0',
    41: 'COMPLEXITY_1',
    42: 'COMPLEXITY_2',
    43: 'COMPLEXITY_3',
    5: 'ZERO_FUNCTION',
    50: 'LOW_FUNCTION',
    55: 'HIGH_FUNCTION',
    6: 'HIGH_DISCONTINUOUS',
  };
  return names[item] ?? 'ITEM_$item';
}
